apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-scheduler-extender
  labels:
    app: sample-scheduler-extender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-scheduler-extender
  template:
    metadata:
      labels:
        app: sample-scheduler-extender
    spec:
      containers:
      - name: sample-scheduler-extender
        command: ['sh', '-c', '/sample-scheduler-extender']
        image: ghcr.io/vadasambar/sample-scheduler-extender:v1.1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sample-scheduler-extender-service
spec:
  selector:
    app: sample-scheduler-extender
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080